title: Frenyum Network
description: Open-source cryptocurrency network
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Github Repository: https://github.com/Frenyum-Network/frenyum-node
color_scheme: dark

